import './globals.css';

import AuthProvider from './auth/AuthProvider';
import { Inter, Roboto } from 'next/font/google';
import type { Metadata } from 'next';

import Navbar from './components/Navbar';
import NextTopLoader from 'nextjs-toploader';
import GoogleAnalyticsScript from './GoogleAnalyticsScript';

// using a local font
import localFont from 'next/font/local';

const monoLisa = localFont({
  src: '../public/fonts/MonoLisa-Regular.ttf',
  variable: '--font-monolisa', // essential for tailwindcss
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    // read more on opengraph meta tags
    // at minimum title and description suffices
    title: '',
    description: '',
  },
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['500', '400'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' data-theme='winter'>
      <GoogleAnalyticsScript />
      {/* <body className={roboto.className} >*/}
      <body className={monoLisa.className}>
        <AuthProvider>
          <NextTopLoader />
          <Navbar />
          <main className='p-5'>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
