GET http://localhost:3000/api/users


###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": ""
}



###
PUT http://localhost:3000/api/users/10
Content-Type: application/json

{
  "name": "k"
}

###
DELETE http://localhost:3000/api/users/1
Content-Type: application/json

